### ISSUE TITLE
Refreshing competition animation bug

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots-cloud#100]
When clicking the view button in the leaderboard of a competition, the corresponding animation is correctly opened and played.
However, if I refresh the animation page, it cannot reload the animation.
The error: 
`(error) File not found: https://raw.githubusercontent.com/cyberbotics/wrestling/undefined/storage/wb_a`

**Comment by omichel** [comment]
Fixed in 3af4fe68fd43138513518f8583f99c4ecfbd6177.
