### ISSUE TITLE
Running database/webots-cloud.sql gives syntax errors

### ISSUE THREAD

**Issue by moneylobster** [cyberbotics/webots-cloud#104]
**Describe the Bug**

Running ```database/webots-cloud.sql``` on a blank MySQL database gives three syntax errors:

1. a duplicate column error:

(```Duplicate column name 'viewed'```)

Lines ```39``` and ```48``` both create the same ```viewed``` column. Deleting line ```48``` and the comma at the end of line ```47``` seems to solve the error.

2. two additional syntax errors:

(```You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT' at line 1```)

Replacing the semicolons at the end of lines ```53``` and ```105``` with commas seems to solve these errors.

**Steps to Reproduce**
1. Create a new MySQL database
2. ```source``` the file ```webots-cloud.sql``` in the MySQL console
3. Errors pop up during the execution of the file

**Expected behavior**

The script should configure the database without any errors.

**System**
 - Ubuntu 22.04
 - MySQL ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by omichel** [comment]
Thank you @moneylobster for this bug report. It should be fixed in #105.
