### ISSUE TITLE
PROTO subcategories order changes

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots-cloud#144]
For some of the PROTO categories, the order of the subcategories changes after clicking multiple times on the selected category icon.

I can reproduce it for Furniture, Building and Exterior:
![Screenshot from 2023-07-05 09-24-22](https://github.com/cyberbotics/webots-cloud/assets/5910449/ef954a6b-c127-46d1-a8c6-8d20637c5397)

![Screenshot from 2023-07-05 09-24-27](https://github.com/cyberbotics/webots-cloud/assets/5910449/d8dda55c-5e65-403c-a99d-735e52a98e5f)

**Comment by BenjaminDeleze** [comment]
I just checked and it is not really a bug.
The subcategories are order by the number of elements they contains (except for subcategories like `others` that are always at the end).
The subcategories that are switching positions are subcategories that have the same amount of protos in them.

**Comment by stefaniapedrazzi** [comment]
It is strange that the categories changes.
If categories have the same amount of PROTOs, then some other fixed order should be used, like the alphabetocal order.
