### ISSUE TITLE
nvidia-container-cli: initialization error

### ISSUE THREAD

**Issue by skpawar1305** [cyberbotics/webots-cloud#146]
Our simulation: https://webots.cloud/run?version=R2023a&url=https%3A%2F%2Fgithub.com%2FRRL-ALeRT%2Fspot-webots-cloud%2Fblob%2Fmain%2Fworlds%2Fspot.wbt&type=demo

or any other simulation throws

nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown

while loading, and gets stuck there. Everything used to work pretty much 1-2 months ago. Maybe a restart of the server might fix it?

**Comment by omichel** [comment]
Indeed. I updated and rebooted the simulation server and now everything seems to work fine.
