### ISSUE TITLE
Missing texture in "official" scene

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots-cloud#48]
This scene has a missing texture: https://webots.cloud/SchkH69

![aaa](https://user-images.githubusercontent.com/44834743/188097866-afd2bca5-4635-47e4-adf7-efaf823f41cd.png)

This scene is referenced in the R2022b blog post

**Comment by omichel** [comment]
I uploaded the fixed scene at https://webots.cloud/ScjYrg8
The problem was due to a change of the path to the bed cover texture in the R2022b branch.
